---
- name: copy wordpress nginx config
  template:
    src: nginx-wordpress.conf.j2
    dest: /etc/nginx/conf.d/nginx-wordpress.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: insert firewalld rule for {{ nginx_port_with_tls }} and {{ nginx_no_tls_port }} port
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ nginx_no_tls_port }}"
    - "{{ nginx_port_with_tls }}"

- name: install requirement packages
  yum:
    name: "{{ php_packages_list }}"
    update_cache: true
    state: present

- name: remove default /etc/php-fpm.d/www.conf file
  file:
    path: /etc/php-fpm.d/www.conf
    state: absent
  notify: restart php-fpm

- name: copy wordpress.conf from files to /etc/php-fpm.d/wordpress.conf
  copy:
    src: wordpress.conf
    dest: /etc/php-fpm.d/wordpress.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart php-fpm

- name: Download WordPress from http://wordpress.org/wordpress-{{ wp_version }}.tar.gz to /srv/ folder + checksum
  get_url:
    url: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /srv/
    mode: "0644"
    checksum: "{{ wp_checksum }}"

- name: Unarchive wordpress to /srv folder
  unarchive:
    src: /srv/wordpress-{{ wp_version }}.tar.gz
    dest: /srv
    remote_src: true

- name: Add linux group "wordpress"
  group:
    name: wordpress
    state: present

- name: Add linux user "wordpress" with group "wordpress"  and /srv/wordpress as homedir
  user:
    name: wordpress
    group: wordpress
    home: /srv/wordpress

- name: Copy WordPress config file from templates to /srv/wordpress/wp-config.php
  template:
    src: wp-config.php
    dest: /srv/wordpress/wp-config.php
    owner: root
    group: root
    mode: 0644

- name: /srv/wordpress directory recursive rights for wordpress user and group
  file:
    path: /srv/wordpress
    owner: wordpress
    group: wordpress

- name: start and enable php-fpm Service
  service:
    name: php-fpm
    enabled: true
    state: started
