---
- name: install nginx
  yum:
    name: nginx
    update_cache: true
    state: present

- name: copy main nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: ensure nginx is enabled and started
  service:
    name: nginx
    state: started
    enabled: true
