---
- hosts: nodes
  gather_facts: false
  become: true
  vars_files: 
    - ./vars/main.yml
  pre_tasks:
    - name: install python2-pip
      yum:
        name: python2-pip
        update_cache: true
        state: present

    - name: install requirement pip modules
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - pip == 20.3.4 
        - cryptography >= 1.6

    - name: disable selinux
      selinux:
        state: disabled

  roles:
    - configure_certs
    - install_nginx

  post_tasks:
    - name: check "http://{{ ansible_host }}:{{ nginx_port_no_tls }}"
      uri:
        url: "http://{{ ansible_host }}:{{ nginx_port_no_tls }}"
        return_content: true
      connection: local
      register: example_webpage_out
      failed_when: example_webpage_out.status != 200
      when: not tls_enabled

    - name: check "https://{{ ansible_host }}:{{ nginx_port_with_tls }}"
      uri:
        url: "https://{{ ansible_host }}:{{ nginx_port_with_tls }}"
        return_content: true
        validate_certs: no
      connection: local
      register: example_webpage_out
      failed_when: example_webpage_out.status != 200
      when: tls_enabled | bool
