---
- name: configure nginx without tls
  block:
  - name: copy site's nginx config file without tls
    template:
      src: no_tls.conf.j2
      dest: /etc/nginx/conf.d/no_tls.conf
      owner: root
      group: root
      mode: 0644
    notify: restart nginx

  - name: insert firewalld rule for {{ nginx_port_no_tls }} port
    firewalld:
      port: "{{ nginx_port_no_tls }}/tcp"
      permanent: true
      state: enabled
      immediate: true
  when: not tls_enabled
